version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: truck-driver-communication-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/truck-communication
      - LOG_LEVEL=info
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: truck-driver-communication-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=truck-communication
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local 